# Generated by Django 3.2.8 on 2021-10-31 18:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=30)),
                ('cod_postal', models.TextField(max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.TextField(max_length=30)),
                ('cuit', models.TextField(max_length=30)),
                ('direccion', models.TextField(blank=True, default='', max_length=30)),
                ('telefono', models.TextField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('localidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionStock.localidades')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Tmp_Orden_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo_proveedor', models.TextField(blank=True, default='', max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, default='', max_length=30, null=True)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionStock.proveedores')),
            ],
            options={
                'verbose_name_plural': 'Pre Orden de Compra ',
            },
        ),
        migrations.CreateModel(
            name='Tmp_Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuevo', models.BooleanField(default=False, null=True)),
                ('articulo_proveedor', models.TextField(blank=True, default='', max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, default='', max_length=30, null=True)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionStock.proveedores')),
            ],
            options={
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=30)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.paises')),
            ],
            options={
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.AddField(
            model_name='localidades',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.provincias'),
        ),
        migrations.CreateModel(
            name='Configuracion_Listas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabecera', models.TextField(max_length=30)),
                ('tipo_archivo', models.TextField(max_length=30)),
                ('delimitador', models.TextField(max_length=1, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.proveedores')),
            ],
            options={
                'verbose_name_plural': 'Configuracion Listas',
            },
        ),
        migrations.CreateModel(
            name='Configuracion_Columnas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decimal', models.TextField(blank=True, max_length=10, null=True)),
                ('columna_archivo', models.TextField(max_length=10)),
                ('columna_bd', models.TextField(max_length=10)),
                ('lista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionStock.configuracion_listas')),
            ],
            options={
                'verbose_name_plural': 'Configuracion Columnas',
            },
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=30)),
                ('stock', models.IntegerField(default=0)),
                ('marca', models.TextField(blank=True, default='', max_length=30, null=True)),
                ('tipo', models.TextField(blank=True, choices=[('', ''), ('Alimento', 'Alimento'), ('Ropa', 'Ropa'), ('Accesorio', 'Accesorio')], default='', max_length=30)),
                ('articulo_proveedor', models.TextField(blank=True, default='', max_length=30, null=True)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('precio_vta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_actualizacion', models.DateField(default=django.utils.timezone.now)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.proveedores')),
            ],
            options={
                'verbose_name_plural': 'Articulos',
            },
        ),
    ]
