# Generated by Django 3.2.7 on 2021-11-02 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tmp_orden_compra',
            options={'verbose_name_plural': 'Pre Orden de Compra'},
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, default='', max_length=30, null=True)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionStock.proveedores')),
            ],
            options={
                'verbose_name_plural': 'Orden de Compra',
            },
        ),
    ]
