# Generated by Django 3.2.3 on 2021-06-28 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0002_alter_localidades_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Altas',
            fields=[
                ('num_factura', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Altas',
            },
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=30)),
                ('stock', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Articulos',
            },
        ),
        migrations.CreateModel(
            name='Articulos_Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo_proveedor', models.TextField(max_length=30)),
                ('descripcion_articulo_proveedor', models.TextField(max_length=10, null=True)),
                ('articulo', models.IntegerField()),
                ('precio_costo', models.IntegerField()),
                ('fecha_actualizacion', models.TextField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Articulos Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Bajas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('stock_max', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Bajas',
            },
        ),
        migrations.CreateModel(
            name='Configuracion_Columnas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dato', models.TextField(max_length=10)),
                ('decimal', models.TextField(max_length=10, null=True)),
                ('miles', models.TextField(max_length=10, null=True)),
                ('columna_archivo', models.IntegerField()),
                ('columna_bd', models.IntegerField()),
                ('delimitador', models.TextField(max_length=10, null=True)),
                ('cant_caracteres', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Configuracion Columnas',
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(max_length=30)),
                ('origen', models.TextField(max_length=30, null=True)),
                ('web', models.TextField(max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(max_length=30)),
                ('fecha_vencimiento', models.DateField(null=True)),
                ('punto_pedido', models.TextField(max_length=30, null=True)),
                ('stock_max', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.CreateModel(
            name='Tipos_Salidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos Salidas',
            },
        ),
        migrations.AlterModelOptions(
            name='localidades',
            options={'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='paises',
            options={'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='provincias',
            options={'verbose_name_plural': 'Provincias'},
        ),
        migrations.CreateModel(
            name='Salidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.articulos')),
                ('cantidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.tipos_salidas')),
                ('id_baja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.bajas')),
            ],
            options={
                'verbose_name_plural': 'Bajas',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.TextField(max_length=30)),
                ('cuit', models.TextField(max_length=30)),
                ('direccion', models.TextField(max_length=30)),
                ('telefono', models.TextField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.localidades')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.TextField(max_length=10, null=True)),
                ('precio_compra', models.IntegerField()),
                ('id_articulo_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.articulos_proveedores')),
                ('num_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.altas')),
            ],
            options={
                'verbose_name_plural': 'Entradas',
            },
        ),
        migrations.CreateModel(
            name='Configuracion_Listas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabecera', models.TextField(max_length=30)),
                ('tipo_archivo', models.TextField(max_length=30)),
                ('telefono', models.TextField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.localidades')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.proveedores')),
            ],
            options={
                'verbose_name_plural': 'Configuracion Listas',
            },
        ),
        migrations.AddField(
            model_name='bajas',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.tipos_salidas'),
        ),
        migrations.AddField(
            model_name='articulos_proveedores',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.proveedores'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.marcas'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.tipos'),
        ),
        migrations.AddField(
            model_name='altas',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.proveedores'),
        ),
    ]
