# Generated by Django 3.2.3 on 2021-06-28 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0004_auto_20210628_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='altas',
            old_name='proveedor_id',
            new_name='proveedor',
        ),
    ]
