# Generated by Django 3.2.3 on 2021-06-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0005_rename_proveedor_id_altas_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bajas',
            name='stock_max',
        ),
        migrations.RemoveField(
            model_name='configuracion_listas',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='configuracion_listas',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='configuracion_listas',
            name='telefono',
        ),
        migrations.AddField(
            model_name='localidades',
            name='cod_postal',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
