# Generated by Django 3.2.3 on 2021-10-18 01:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0007_rename_mail_proveedores_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos_proveedores',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='bajas',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='entradas',
            name='id_articulo_proveedor',
        ),
        migrations.RemoveField(
            model_name='entradas',
            name='num_factura',
        ),
        migrations.RemoveField(
            model_name='salidas',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='salidas',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='salidas',
            name='id_baja',
        ),
        migrations.RemoveField(
            model_name='configuracion_columnas',
            name='delimitador',
        ),
        migrations.AddField(
            model_name='articulos',
            name='articulo_proveedor',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='articulos',
            name='fecha_actualizacion',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 1, 54, 3, 486561, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='articulos',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulos',
            name='precio_vta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulos',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionStock.proveedores'),
        ),
        migrations.AddField(
            model_name='configuracion_columnas',
            name='lista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionStock.configuracion_listas'),
        ),
        migrations.AddField(
            model_name='configuracion_listas',
            name='delimitador',
            field=models.TextField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='marca',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='tipo',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Altas',
        ),
        migrations.DeleteModel(
            name='Articulos_Proveedores',
        ),
        migrations.DeleteModel(
            name='Bajas',
        ),
        migrations.DeleteModel(
            name='Entradas',
        ),
        migrations.DeleteModel(
            name='Marcas',
        ),
        migrations.DeleteModel(
            name='Salidas',
        ),
        migrations.DeleteModel(
            name='Tipos',
        ),
        migrations.DeleteModel(
            name='Tipos_Salidas',
        ),
    ]
