# Generated by Django 3.2.3 on 2021-10-18 01:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0008_auto_20211017_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='fecha_actualizacion',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 1, 56, 3, 224627, tzinfo=utc)),
        ),
    ]
