# Generated by Django 3.2.3 on 2021-10-18 02:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0009_alter_articulos_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='fecha_actualizacion',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 2, 1, 36, 994318, tzinfo=utc)),
        ),
    ]
