# Generated by Django 3.2.3 on 2021-10-18 02:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0010_alter_articulos_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='fecha_actualizacion',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 2, 15, 14, 601971, tzinfo=utc), null=True),
        ),
    ]
