# Generated by Django 3.2.3 on 2021-10-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0015_alter_articulos_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='fecha_actualizacion',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
