# Generated by Django 3.2.3 on 2021-10-18 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0018_remove_articulos_fecha_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='fecha_actualizacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
