# Generated by Django 3.2.3 on 2021-10-18 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0019_articulos_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='articulo_proveedor',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='proveedor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestionStock.proveedores'),
        ),
        migrations.AlterField(
            model_name='configuracion_columnas',
            name='decimal',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='configuracion_columnas',
            name='miles',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='direccion',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='localidad',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestionStock.localidades'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='telefono',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
