# Generated by Django 3.2.3 on 2021-10-18 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0024_alter_articulos_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='articulo_proveedor',
            field=models.TextField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='direccion',
            field=models.TextField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='localidad',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='gestionStock.localidades'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='telefono',
            field=models.TextField(blank=True, default='', max_length=30),
        ),
    ]
