# Generated by Django 3.2.3 on 2021-10-25 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0026_auto_20211025_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='proveedor',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionStock.proveedores'),
        ),
    ]
