# Generated by Django 3.2.3 on 2021-10-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0027_alter_articulos_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='articulo_proveedor',
            field=models.TextField(blank=True, default='', max_length=30, null=True),
        ),
    ]
