# Generated by Django 3.2.3 on 2021-10-26 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0029_alter_articulos_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='marca',
            field=models.TextField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='precio_vta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='proveedor',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionStock.proveedores'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='tipo',
            field=models.TextField(blank=True, choices=[('', ''), ('Alimento', 'Alimento'), ('Ropa', 'Ropa'), ('Accesorio', 'Accesorio')], default='', max_length=30),
        ),
    ]
