# Generated by Django 3.2.3 on 2021-10-27 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0031_auto_20211027_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.proveedores'),
        ),
    ]
