# Generated by Django 3.2.3 on 2021-10-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0033_tmp_articulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmp_articulos',
            name='insert',
            field=models.BooleanField(default=False),
        ),
    ]
