# Generated by Django 3.2.3 on 2021-10-29 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0034_alter_tmp_articulos_insert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmp_articulos',
            name='insert',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tmp_articulos',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='tmp_articulos',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionStock.proveedores'),
        ),
    ]
